services:
    frontend:
        build:
            context: frontend
            target: development
        ports:
            - 3000:3000
        stdin_open: true
#        volumes:
#            - .\frontend:/usr/src/app
        container_name: frontend
        restart: always
        networks:
            - react-express

    backend:
        container_name: backend
        restart: always
        build:
            context: backend
            target: development
#        volumes:
#            - .\backend:/usr/src/app
        networks:
            - react-express
            - express-mongo
        expose: 
            - 3000
    mongo:
        container_name: mongo
        restart: always
        image: mongo
#        volumes:
#            - .\dbdata:/data/db
#            - .\dbconfig:/data/configdb
        networks:
            - express-mongo
        expose:
            - 8081:8081
        ports:
            - 27017:27017
#volumes:
#    frontend:
#    backend:
#    dbdata:
#    dbconfig:

networks:
    react-express:
    express-mongo:
